version: '3'
services:
  # -----------------------------------------------------------
  # 1. ZOOKEEPER (Required for Kafka)
  # -----------------------------------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # -----------------------------------------------------------
  # 2. KAFKA (Version 3.5 - Compatible with your Spark 3.4)
  # -----------------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # IMPORTANT: Allows you to connect from your local Python scripts via 'localhost:9092'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Auto-creates your project topics
      KAFKA_CREATE_TOPICS: "raw_transactions:1:1,fraud_alerts:1:1"

  # -----------------------------------------------------------
  # 3. REDIS (Your "Battle Scar" Database)
  # -----------------------------------------------------------
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"